### ISSUE TITLE
question?

### ISSUE THREAD

**Issue by zhao9752** [hulu88/PMT#1]
I tried these model parameters(in the GoogleDrive link), but didn't achieve the desired result.

Datasets | Backbone | Rank@1 | mAP | mINP | Model
-- | -- | -- | -- | -- | --
#SYSU-MM01 | ViT | ~ 67.53% | ~ 64.98% | ~51.86% | GoogleDrive
#SYSU-MM01 | AGW* | ~ 67.09% | ~ 64.25% | ~50.89% | GoogleDrive

![1679318418087](https://user-images.githubusercontent.com/43698221/226351239-ee90c31b-bcd4-41a0-b3fc-6d60b8ea1bd2.png)

**Comment by zhao9752** [comment]
there maybe have a problem with the saved model, and retraining it may lead to the desired results.

**Comment by GG0614** [comment]
> there maybe have a problem with the saved model, and retraining it may lead to the desired results.

你好 请问你解决这个问题了吗 我也遇到了这个问题
